# Generated by Django 5.1 on 2024-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talle_peso',
            field=models.CharField(max_length=50),
        ),
    ]
